apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name | trunc 63 | trimSuffix "-"}}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm-chart.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "helm-chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}